name: "Build"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        system: [terrestrial, satellite]
    steps:
    - uses: actions/checkout@v4
    - name: Build nixos configuration
      run: nix build -L .#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel
    - name: Get nix store path
      run: readlink -f result > store.txt
    - name: Archive configuration
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.system }}
        path: store.txt
