name: "Build"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build nixos configuration
      run: nix build -L .#nixosConfigurations.terrestrial.config.system.build.toplevel^C
    - name: Archive configuration
      uses: actions/upload-artifact@v4
      with:
        name: terrestrial
        path: result/
