name: "Build"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        system: [terrestrial, satellite]
    steps:
    - uses: actions/checkout@v3
    - name: Build nixos configuration
      run: nix build -L .#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel
    - name: Tar configuration
      run: tar -hcvf result.tar result/ || [[ $? -eq 1 ]]
    - name: Archive configuration
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.system }}
        path: result.tar
