name: "Update"
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Update flake
      run: nix flake update
    - name: Check flake
      run: nix flake check
    - name: Commit lockfile
      uses: EndBug/add-and-commit@v9
      with:
        add: 'flake.lock'
        path: store.txt
        message: 'Weekly flake update'
